# Generated by Django 2.0.6 on 2019-09-30 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookKeeperApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publishDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
